let cities = [ "dmitrii_ivan01", "w6pjjuygh", "Whitehallian🏛", "myakshang", "Myaksang Limbu", "abhinav_subba07", "mr._.thapa30", "Thp Giraffe", "tank_esports_siliguri", "Tank Esports Silliguri", "whitehallian3", "aps_confession00", "_arvin.mfs", "StraNge 👾", "_limbu_k", "limbu_kunal_", "_anwesha.sewa_", "_anmolthapa_", "Anmol Thapa", "a4dhi.yaa", "☆", "krishurai_", "krishurai", "bishnuchhetri9021", "Bishnu Chhetri", "choeen__", "choden sherpa~", "dee_dixa", "Dikcha Tamang", "maan.s19", "Mansha Pun", "_reb_.oo", "s_.sherpa", "siwangi", "__stoic__0", "Smith P", "lx_hurricanesf", "🎸🎧", "_cloudsylw", "anuska🍒", "nor._.d_", ".", "aps_confession_23", "APS_CONFESS~", "orphic011", ":/", "ashimmenyangbo", "Ashim Limbu", "_rai_ansh_08", "bunny rai", "tulipc0re_", "Tulip~", "neeraj.kr._.3.8", "Neeraj", "kuxiqq_", "xî", "stvryy_mei", "kashturi", "kushalrowth_", "Küzëñ 🂡", "iamaryanchhetri", "🎧 R yan", "li_mbu_ni_26", "_bistazzz_4", "Ｓｉｄｄｈａｎｔ 🕷", "numsnn", "Numa Ningleku", "harsitadon_", "harsitachettri🐣", "dumbos_s", "⛇☃︎", "luvley_.blis", "@𝓵𝓾𝓿._𝓵𝓮𝔂", "shi_vam0603", "Shivam", "vishal.limbu1", "Vishall", "_0_0_niyati", "ニニ", "dro._.naaahhh", "D", "judaas_in_my_mind", "Anurag Bantawa Rai", "blue_berries__15", "🚩", "abandoned7900", "sr_.core", "Eqo", "shrntpa", "Sharon Thapa", "judaas_iscariot", "Anurag Rai", "ss013st", "sushant", "dipesh.raiiiii", "dipeshrai", "sing_with_n.moktan", "Nima_tmz", "_rehan_thapa_", "Rehan", "alkrawn145", "Dolma lepcha", "itzdelta456", "Delta Zakuro", "suz.crochet", "Suzette🎀", "dikchen__sherpa18", "dikilaa", "im_bat_boy_11", "Asha Oraon", "__aishiteru._", "Paras Thapa", "aryan.goyary", "𝙎𝙂𝙄—× 𝙍𝙀𝘼𝙋𝙀𝙍", "swe3.kriti", "Swikriti Adhikari", "unknowngalaxy25", "ADITYA KUMAR", "confessout_apssukna", "APS SUKNA", "_pvt_haishayad", "_phombo_limbu_", "dewa.kar_", "🌕", "sohan_mukhiya_", "shahil.thapa_", "youkonwshahil 🐎", "lopsang__sherpa__7", "L.S", "aka_ns.ha11", "_.dev6_", "Dev rai 🎸", "niyatichem", "joli", "chhetri_harshit_", "Harshit Poudel", "apssukna.pvt", "it_me_marsel", "Nirmal Tigga", "esmart_stranger", "Good stranger 🗿", "_wh0ss_", "Simrann", "ch987st", "christinaaa", "pallab.gurung", "Pallab Gurung", "smirt3_thapa", "s.🪬", "norr._07", "angelina.", "riiiddhhi._ch_", "🐹", "jolly_rai7", "Jolly Rai" ];

let heroes = [ "dmitrii_ivan01", "w6pjjuygh", "Whitehallian🏛", "myakshang", "Myaksang Limbu", "abhinav_subba07", "mr._.thapa30", "Thp Giraffe", "tank_esports_siliguri", "Tank Esports Silliguri", "whitehallian3", "aps_confession00", "_limbu_k", "limbu_kunal_", "_anwesha.sewa_", "_anmolthapa_", "Anmol Thapa", "a4dhi.yaa", "☆", "krishurai_", "krishurai", "bishnuchhetri9021", "Bishnu Chhetri", "choeen__", "choden sherpa~", "dee_dixa", "Dikcha Tamang", "maan.s19", "Mansha Pun", "_reb_.oo", "s_.sherpa", "siwangi", "__stoic__0", "Smith P", "lx_hurricanesf", "🎸🎧", "_cloudsylw", "anuska🍒", "nor._.d_", ".", "aps_confession_23", "APS_CONFESS~", "orphic011", ":/", "ashimmenyangbo", "Ashim Limbu", "_rai_ansh_08", "bunny rai", "tulipc0re_", "Tulip~", "kuxiqq_", "xî", "stvryy_mei", "kashturi", "kushalrowth_", "Küzëñ 🂡", "iamaryanchhetri", "🎧 R yan", "li_mbu_ni_26", "_bistazzz_4", "Ｓｉｄｄｈａｎｔ 🕷", "numsnn", "Numa Ningleku", "harsitadon_", "harsitachettri🐣", "mcshnizzle", "Keiani Mabe", "luvley_.blis", "@𝓵𝓾𝓿._𝓵𝓮𝔂", "shi_vam0603", "Shivam", "_0_0_niyati", "ニニ", "dro._.naaahhh", "D", "judaas_in_my_mind", "Anurag Bantawa Rai", "blue_berries__15", "🚩", "zachardson", "Zach Richardson | Performance Coach", "abandoned7900", "sr_.core", "Eqo", "shrntpa", "Sharon Thapa", "sujuma_basumatary_", "Suz", "dipesh.raiiiii", "dipeshrai", "alkrawn145", "Dolma lepcha", "_rehan_thapa_", "Rehan", "judaas_iscariot", "Anurag Rai", "dikchen__sherpa18", "dikilaa", "andweaso", "Andrea So", "suz.crochet", "Suzette🎀", "aryan.goyary", "𝙎𝙂𝙄—× 𝙍𝙀𝘼𝙋𝙀𝙍", "an_ilspace", "Αηιℓ", "swe3.kriti", "Swikriti Adhikari", "unknowngalaxy25", "ADITYA KUMAR", "_pvt_haishayad", "_phombo_limbu_", "confessout_apssukna", "APS SUKNA", "dewa.kar_", "🌕", "lopsang__sherpa__7", "L.S", "_.smritistha07", "Stha.🎧☆", "aka_ns.ha11", "theyakthungs", "The Limbus", "_.dev6_", "Dev rai 🎸", "avemoves", "AVE", "theanimemen", "TheAnimeMen", "niyatichem", "joli", "sujuka_basumatary", "apssukna.pvt", "maybe_riwaj_gurung_", "Riwaj 💤💤", "ch987st", "christinaaa", "norr._07", "angelina.", "jolly_rai7", "Jolly Rai", "sbjsvssjsv13", "dhat_ri_ka_ dj13", "yeager.tt", "YEAGER", "aps__confession2024", "APSS", "pranay_thaapa", "Pranay Thapa", "xo.aryan__", "who_.aryan🌀", "riri_magar", "riya", "_unforgettwble_i", "~ishu~🫧🌷", "_wh0ss_", "Simrann", "smirt3_thapa" ];

let setCities = new Set(cities);
// let setHeroes = new Set(heroes);

// let uncommon = [
//     ...cities.filter(city => !setHeroes.has(city)),
//     ...heroes.filter(hero => !setCities.has(hero))
// ];

// console.log("Uncommon elements:", uncommon);

let missingFromCities = heroes.filter(hero => !setCities.has(hero));

console.log("Missing elements from cities:", missingFromCities);